type Query {
  goodchatProfile: Staff!
  conversations(limit: Int, after: Int, type: ConversationType): [Conversation!]!
  conversation(id: Int!): Conversation
  customers(
    limit: Int,
    after: Int,
    externalId: [String!],
    id: [Int!]
  ): [Customer!]!
}

type Subscription {
  messageEvent(conversationId: Int, actions: [SubscriptionAction]): MessageEvent!
  readReceiptEvent(conversationId: Int!): ReadReceiptEvent!
}

type Mutation {
  # TODO: Mutations
  #   - JoinConversation(conversation)
  #   - AddToConversation(user, conversation)
  #   - LeaveConversation(conversation)
  #   - createConversation(private?)
  #   - sendImage
  #   - sendLocation
  #   - sendLink
  #   - sendXXX

  sendMessage(
    conversationId: Int!,
    text: String!,
    timestamp: DateTime,
    metadata: JSON
  ) : Message!
  startTyping(conversationId: Int!) : Conversation!
  stopTyping(conversationId: Int!) : Conversation!
  markAsRead(conversationId: Int!) : ReadReceipt!
}

enum ConversationType {
  CUSTOMER
  PRIVATE
  PUBLIC
}

enum SubscriptionAction {
  CREATE
  UPDATE
  DELETE
}

type ReadReceipt {
  id: Int!
  userId: Int!
  userType: String!
  conversationId: Int!
  conversation: Conversation!
  lastReadMessageId: Int!
  lastReadMessage: Message!
  createdAt: DateTime!
  updatedAt: DateTime!
}

type Conversation {
  id: Int!
  customerId: Int
  customer: Customer
  source: String!
  type: ConversationType!
  metadata: JSON!
  createdAt: DateTime!
  updatedAt: DateTime!
  messages(limit: Int, after: Int): [Message!]!
  readReceipts: [ReadReceipt!]!
  staffs: [Staff!]!
}

type Message {
  id: Int!
  createdAt: DateTime!
  updatedAt: DateTime!
  conversationId: Int!
  conversation: Conversation!
  authorType: String!
  authorId: Int!
  content: JSON!
  metadata: JSON!
}

type MessageEvent {
  action: SubscriptionAction!
  message: Message!
}

type ReadReceiptEvent {
  action: SubscriptionAction!
  readReceipt: ReadReceipt!
}

type Customer {
  id: Int!
  externalId: String
  createdAt: DateTime!
  displayName: String!
  email: String
  avatarUrl: String
  locale: String!
  metadata: JSON!
  conversations: [Conversation!]!
}

type Staff {
  id: Int!
  createdAt: DateTime!
  updatedAt: DateTime!
  externalId: String
  displayName: String!
  metadata: JSON!
  permissions: [String!]!,
  conversations: [Conversation!]!
}
