# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - goodchat-api-staging

on:
  push:
    branches:
      - main
      - gh-workflow-*
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
      postgres:
        image: postgres
        env:
          POSTGRES_USER: testuser@test_database
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: test_database
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@master

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Use NPM 7
      run: npm install --global npm@7

    - name: Run Specs
      env:
        DB_CREDENTIALS: "testuser@test_database:testpassword"
        DB_NAME: "test_database"
      run: |
        npm install
        npm run db:migrate:test
        npm run test:coverage

    - name: CODECOV
      run: npx codecov --token="${{secrets.CODECOV_TOKEN}}"
      env:
        npm_config_yes: true

    - name: Build project
      run: npm run build

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'goodchat-api-staging'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6632a23b6f7e4fa0ace2de7a58ea4d47 }}
        package: .
